import type { Config } from "./archstrict.types.js";

// Checks source dependency layers; test fixtures stay outside the architectural module graph.
export default {
  schemaVersion: 1,
  surface: ["index.ts", "index.tsx", "index.mts", "index.cts"],
  exclude: [
    "archstrict.config.ts",
    "archstrict.types.ts",
    ".*/**",
    "**/.*/**",
    "test/**",
  ],
  declaredModules: [
    { name: "cli.ts", glob: "src/cli.ts", surface: "cli.ts" },
    { name: "cli-commands.ts", glob: "src/cli-commands.ts", surface: "cli-commands.ts" },
    { name: "cli-human.ts", glob: "src/cli-human.ts", surface: "cli-human.ts" },
    { name: "cli-diagnostics.ts", glob: "src/cli-diagnostics.ts", surface: "cli-diagnostics.ts" },
    { name: "cli-help.ts", glob: "src/cli-help.ts", surface: "cli-help.ts" },
    { name: "cloud-client", glob: "src/cloud-client/**", surface: "index.ts" },
    { name: "cloudflare.config.ts", glob: "cloudflare.config.ts", surface: "cloudflare.config.ts" },
    { name: "scripts", glob: "scripts/**" },
    { name: "vite.config.ts", glob: "vite.config.ts", surface: "vite.config.ts" },
    { name: "records", glob: "src/records/**", surface: ["index.ts", "persistence.ts"] },
    { name: "local-store", glob: "src/local-store/**", surface: "index.ts" },
    { name: "workspace", glob: "src/workspace/**", surface: "index.ts" },
    { name: "host-hooks", glob: "src/host-hooks/**", surface: "index.ts" },
    { name: "service", glob: "src/service/**", surface: "index.ts" },
    { name: "transition", glob: "src/transition/**", surface: "index.ts" },
  ],
  classify: [
    { glob: "src/cli.ts", tags: ["layer:entrypoint", "env:node"] },
    { glob: "src/cli-commands.ts", tags: ["layer:entrypoint", "env:node"] },
    { glob: "src/cli-diagnostics.ts", tags: ["layer:entrypoint", "env:node"] },
    { glob: "src/cli-help.ts", tags: ["layer:entrypoint", "env:node"] },
    { glob: "src/cli-human.ts", tags: ["capability:cli-human", "layer:adapter", "env:portable"] },
    { glob: "src/cloud-client/**", tags: ["capability:cloud-client", "layer:adapter", "env:node"] },
    { glob: "cloudflare.config.ts", tags: ["layer:entrypoint"] },
    { glob: "scripts/**", tags: ["layer:entrypoint"] },
    { glob: "vite.config.ts", tags: ["layer:entrypoint"] },
    { glob: "src/records/**", tags: ["capability:records", "layer:domain", "env:portable"] },
    { glob: "src/local-store/**", tags: ["capability:local-store", "layer:adapter", "env:node"] },
    { glob: "src/workspace/**", tags: ["capability:workspace", "layer:adapter", "env:node"] },
    { glob: "src/host-hooks/**", tags: ["capability:host-hooks", "layer:adapter", "env:node"] },
    { glob: "src/service/**", tags: ["capability:service", "layer:adapter", "env:worker"] },
    { glob: "src/service/index.ts", tags: ["capability:service", "layer:entrypoint", "env:worker"] },
    { glob: "src/transition/**", tags: ["capability:transition", "layer:core", "env:portable"] },
  ],
  edges: {
    allowDeny: [
      { source: "env:node", targetNamespace: "env", deny: ["worker"], because: "The CLI client must not depend on the Worker service." },
      { source: "env:worker", targetNamespace: "env", deny: ["node"], because: "The Worker must not load local configuration or credentials." },
      { source: "env:portable", targetNamespace: "pkg", deny: ["node"], because: "Record behavior must stay portable across storage runtimes." },
      { source: "env:worker", targetNamespace: "pkg", deny: ["node"], because: "Worker code must not load Node builtins." },
      { source: "capability:cli-human", targetNamespace: "capability", allow: ["cli-human","records"], because: "Human output formats issue reads without depending on storage or credentials." },
      { source: "capability:local-store", targetNamespace: "capability", allow: ["local-store","records"], because: "local-store imports only the capability contracts it uses." },
      { source: "capability:workspace", targetNamespace: "capability", allow: ["workspace","records"], because: "workspace imports only the capability contracts it uses." },
      { source: "capability:host-hooks", targetNamespace: "capability", allow: ["host-hooks","records"], because: "host-hooks imports only the capability contracts it uses." },
      { source: "capability:cloud-client", targetNamespace: "capability", allow: ["cloud-client","records","workspace"], because: "cloud-client imports only the capability contracts it uses." },
      { source: "capability:service", targetNamespace: "capability", allow: ["service","records"], because: "service imports only the capability contracts it uses." },
    ],
    order: [
      {
        tagNamespace: "layer",
        sequence: { "": ["core", "domain", "adapter", "entrypoint"] },
        direction: "downward-only",
        because: "Transition decisions stay independent of SQL; domain behavior stays independent of storage, credentials, and transport; adapters implement domain ports; command and Worker entrypoints consume both.",
      },
    ],
  },
  because: "The dependency order keeps issue and memory behavior independent from storage, credentials, and transport.",
} satisfies Config;
