import type { Config } from "./archstrict.types.js";

// Checks source dependency layers; test fixtures stay outside the architectural module graph.
export default {
  schemaVersion: 1,
  surface: ["index.ts", "index.tsx", "index.mts", "index.cts"],
  exclude: [
    "archstrict.config.ts",
    "archstrict.types.ts",
    ".*/**",
    "**/.*/**",
    "test/**",
  ],
  declaredModules: [
    { name: "access.ts", glob: "src/access.ts", surface: "access.ts" },
    { name: "agent-hooks.ts", glob: "src/agent-hooks.ts", surface: "agent-hooks.ts" },
    { name: "cli.ts", glob: "src/cli.ts", surface: "cli.ts" },
    { name: "cloud-client", glob: "src/cloud-client/**", surface: "index.ts" },
    { name: "connections.ts", glob: "src/connections.ts", surface: "connections.ts" },
    { name: "d1.ts", glob: "src/d1.ts", surface: "d1.ts" },
    { name: "issue-id.ts", glob: "src/issue-id.ts", surface: "issue-id.ts" },
    { name: "issue-queries.ts", glob: "src/issue-queries.ts", surface: "issue-queries.ts" },
    { name: "issues.ts", glob: "src/issues.ts", surface: "issues.ts" },
    { name: "local-config.ts", glob: "src/local-config.ts", surface: "local-config.ts" },
    { name: "memories.ts", glob: "src/memories.ts", surface: "memories.ts" },
    { name: "operations.ts", glob: "src/operations.ts", surface: "operations.ts" },
    { name: "schema.ts", glob: "src/schema.ts", surface: "schema.ts" },
    { name: "snapshot.ts", glob: "src/snapshot.ts", surface: "snapshot.ts" },
    { name: "solarsql.generated.ts", glob: "src/solarsql.generated.ts", surface: "solarsql.generated.ts" },
    { name: "sqlite.ts", glob: "src/sqlite.ts", surface: "sqlite.ts" },
    { name: "worker.ts", glob: "src/worker.ts", surface: "worker.ts" },
    { name: "cloudflare.config.ts", glob: "cloudflare.config.ts", surface: "cloudflare.config.ts" },
    { name: "scripts", glob: "scripts/**" },
    { name: "vite.config.ts", glob: "vite.config.ts", surface: "vite.config.ts" },
  ],
  classify: [
    { glob: "src/access.ts", tags: ["layer:adapter", "env:worker"] },
    { glob: "src/agent-hooks.ts", tags: ["layer:adapter", "env:node"] },
    { glob: "src/cli.ts", tags: ["layer:entrypoint", "env:node"] },
    { glob: "src/cloud-client/**", tags: ["layer:adapter", "env:node"] },
    { glob: "cloudflare.config.ts", tags: ["layer:entrypoint"] },
    { glob: "src/connections.ts", tags: ["layer:adapter", "env:node"] },
    { glob: "src/d1.ts", tags: ["layer:adapter", "env:worker"] },
    { glob: "src/issue-id.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "src/issue-queries.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "src/issues.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "src/local-config.ts", tags: ["layer:adapter", "env:node"] },
    { glob: "src/memories.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "src/operations.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "src/schema.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "scripts/**", tags: ["layer:entrypoint"] },
    { glob: "src/snapshot.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "src/solarsql.generated.ts", tags: ["layer:domain", "env:portable"] },
    { glob: "src/sqlite.ts", tags: ["layer:adapter", "env:node"] },
    { glob: "vite.config.ts", tags: ["layer:entrypoint"] },
    { glob: "src/worker.ts", tags: ["layer:entrypoint", "env:worker"] },
  ],
  edges: {
    allowDeny: [
      { source: "env:node", targetNamespace: "env", deny: ["worker"], because: "The CLI client must not depend on the Worker service." },
      { source: "env:worker", targetNamespace: "env", deny: ["node"], because: "The Worker must not load local configuration or credentials." },
      { source: "env:portable", targetNamespace: "pkg", deny: ["node"], because: "Record behavior must stay portable across storage runtimes." },
      { source: "env:worker", targetNamespace: "pkg", deny: ["node"], because: "Worker code must not load Node builtins." },
    ],
    order: [
      {
        tagNamespace: "layer",
        sequence: { "": ["domain", "adapter", "entrypoint"] },
        direction: "downward-only",
        because: "Domain behavior stays independent of storage, credentials, and transport; adapters implement domain ports; command and Worker entrypoints consume both.",
      },
    ],
  },
  because: "The dependency order keeps issue and memory behavior independent from storage, credentials, and transport.",
} satisfies Config;
